### ISSUE TITLE
Contributions Guide

### ISSUE THREAD

**Issue by austinbaccus** [DerrikCreates/Halo-Infinite-Forge-For-Blender#1]
Are there any rules/guidelines for contributing to this project? I would love to help if I can.

**Comment by DerrikCreates** [comment]
Not currently. Everything is very unorganized right now. https://github.com/joshf67/InfiniteForgeConstants and https://github.com/joshf67/InfiniteForgePacker are a bit more organized. you might have an easier time contributing there for now. Regardless if there is something you want to change make an issue.
